version: '3'
services:
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    # mongo:
    #     image: mongo:latest
    #     ports:
    #         - 27017:27017
    #     restart: always
    #     volumes:
    #         - /data/mongodb:/data/db

    shard1:
        image: mongo:latest
        command: mongod --shardsvr --dbpath /data/db --replSet shard1 --bind_ip_all
        restart: always
        container_name: shard1
        depends_on:
            - config1
            - config2
            - config3
        volumes:
            - /data/mongodb/shard1/data/db:/data/db
            - /data/mongodb/shard1/data/configdb:/data/configdb

    shard2:
        image: mongo:latest
        command: mongod --shardsvr --directoryperdb --replSet shard2 --bind_ip_all
        restart: always
        container_name: shard2
        depends_on:
            - shard1
        volumes:
            - /data/mongodb/shard2:/data/db

    shard3:
        image: mongo:latest
        command: mongod --shardsvr --directoryperdb --replSet shard3 --bind_ip_all
        restart: always
        container_name: shard3
        depends_on:
            - shard2
        volumes:
            - /data/mongodb/shard3:/data/db

    config1:
        image: mongo:latest
        container_name: config1
        restart: always
        command: mongod --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config1:/data/configdb

    config2:
        image: mongo:latest
        container_name: config2
        restart: always
        command: mongod --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config2:/data/configdb

    config3:
        image: mongo:latest
        container_name: config3
        restart: always
        command: mongod --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config3:/data/configdb

    mongos:
        image: mongo:latest
        command: mongos --configdb mongo-config-server/config1:27019,config2:27019,config3:27019 --bind_ip 0.0.0.0 --port 27017
        container_name: mongos
        ports:
            - 27017:27017
        restart: always
        depends_on:
            - config1
            - config2
            - config3
            - shard1
        volumes:
            - /data/mongodb/mongos1:/data/configdb

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6379:6379
        hostname: redis
        restart: always   
        volumes:
            - /data/redis:/data/redis
    