version: '3'
services:
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    shard1:
        image: mongo:latest
        command: --shardsvr --dbpath /data/db --replSet shard1 --bind_ip_all
        restart: always
        container_name: shard1
        volumes:
            - /data/mongodb/shard1:/data/db

    shard2:
        image: mongo:latest
        command: --shardsvr --directoryperdb --replSet shard2 --bind_ip_all
        restart: always
        container_name: shard2
        volumes:
            - /data/mongodb/shard2:/data/db

    shard3:
        image: mongo:latest
        command: --shardsvr --directoryperdb --replSet shard3 --bind_ip_all
        restart: always
        container_name: shard3
        volumes:
            - /data/mongodb/shard3:/data/db

    config1:
        image: mongo:latest
        container_name: config1
        restart: always
        command: --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config1:/data/configdb

    config2:
        image: mongo:latest
        container_name: config2
        restart: always
        command: --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config2:/data/configdb

    config3:
        image: mongo:latest
        container_name: config3
        restart: always
        command: --configsvr --directoryperdb --replSet mongo-config-server --bind_ip_all
        volumes:
            - /data/mongodb/config3:/data/configdb

    mongos:
        image: mongo:latest
        command: mongos --configdb mongo-config-server/config1:27019,config2:27019,config3:27019 --bind_ip 0.0.0.0 --port 27017
        container_name: mongos
        ports:
            - 27017:27017
        restart: always
        depends_on:
            - config1
            - config2
            - config3

    redis-1:
        image: redis:alpine
        container_name: redis-1
        restart: always
        ports:
            - 6379:6379
            - 16379:16379
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-1:/data/redis
            - ./config/redis1.conf:/usr/local/etc/redis/redis.conf
                
    redis-2:
        image: redis:alpine
        container_name: redis-2
        restart: always
        ports:
            - 6380:6380
            - 16380:16380
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-2:/data/redis
            - ./config/redis2.conf:/usr/local/etc/redis/redis.conf

    redis-3:
        image: redis:alpine
        container_name: redis-3
        restart: always
        ports:
            - 6381:6381
            - 16381:16381
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-3:/data/redis
            - ./config/redis3.conf:/usr/local/etc/redis/redis.conf

    redis-4:
        image: redis:alpine
        container_name: redis-4
        restart: always
        ports:
            - 6382:6382
            - 16382:16382
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-4:/data/redis
            - ./config/redis4.conf:/usr/local/etc/redis/redis.conf

    redis-5:
        image: redis:alpine
        container_name: redis-5
        restart: always
        ports:
            - 6383:6383
            - 16383:16383
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-5:/data/redis
            - ./config/redis5.conf:/usr/local/etc/redis/redis.conf
    
    redis-6:
        image: redis:alpine
        container_name: redis-6
        restart: always
        ports:
            - 6384:6384
            - 16384:16384
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - /data/redis/redis-6:/data/redis
            - ./config/redis6.conf:/usr/local/etc/redis/redis.conf
