version: '3.4'

services:
  mongodb:
    image: mongo
    restart: always
    # volumes:
    #   - 
    networks:
      - webapp-network
  home-depot-system:
    image: home-depot-system
    depends_on:
      - mongodb
    # build: .
    # environment:
    #   NODE_ENV: production
    ports:
      - 7326
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge