@url = http://localhost:7326
# @url = http://106.53.103.186

@json = Content-Type: application/json
@jsonWebToken = Authorization: Bearer {{user_token.response.body.token}}
@adminJsonWebToken = Authorization: Bearer {{admin_token.response.body.token}}
@shoppingcart_id = {{shoppingcart_result.response.body._id}}
@order_id = {{order_result.response.body._id}}

### 注册
# 
# POST /signup
# 注册
# @param email    [邮箱地址]
# @param password [用户密码]
# 
# @name user_token
POST {{url}}/api/user/signup
{{json}}

{
    "email": "ljd9726@163.com",
    "password": "87654321"
}

### 登录
# 
# POST /login
# @param email    [邮箱地址]
# @param password [用户密码]
# 
# @name user_token
POST {{url}}/api/user/login
{{json}}

{
    "email": "ljd9726@163.com",
    "password": "87654321"
}

### 发送邮箱验证码
# 
# POST /verifyemail
# 发送带激活邮箱验证码的邮件
# @param email [邮箱地址]
# 
POST {{url}}/api/user/verifyemail
{{json}}

{
    "email": "ljd9726@163.com"
}

### 个人信息
GET {{url}}/api/secure/profile
{{jsonWebToken}}

### 通过产品id获取产品信息(后面是具体需要获取的值)
GET {{url}}/api/product/70171927/{pic_array,desc}

### 通过产品id获取产品信息(全部信息)
GET {{url}}/api/product/70171927/{all}

### 获取根据参数查询的符合的产品信息
GET {{url}}/api/product/all/b_title=家具&s_title=吧台家具&price=100.00-600.00&color=黑色/{price,size,colors}/1

### 根据产品id获取产品库存
GET {{url}}/api/product/70171927/stores/585

### 根据产品id和商场代号添加购物车
# @name shoppingcart_result
POST {{url}}/api/shoppingcart/70171927/585/add
{{jsonWebToken}}
{{json}}

{
    "num": 1
}

### 根据购物车id修改购物车内容
PATCH {{url}}/api/shoppingcart/{{shoppingcart_id}}/update
{{jsonWebToken}}
{{json}}

{
    "num": 5
}

### 获取用户自己所有的购物车
GET {{url}}/api/shoppingcart/all/1/{product_id,num,store_check_name}
{{jsonWebToken}}

### 根据购物车id删除购物车
DELETE {{url}}/api/shoppingcart/{{shoppingcart_id}}/remove
{{jsonWebToken}}

### 根据订单消息提交订单
# @name order_result
POST {{url}}/api/order/70171927/585/add
{{jsonWebToken}}
{{json}}

{
    "first_name": "liang",
    "last_name": "xiaodong",
    "address": "moumouqumoumouzhenmoumoujiemoumoudongmoumoufang",
    "phone": "17345678921",
    "num": 1
}

### 获取用户自己所有的订单
GET {{url}}/api/order/all/1/{all}
{{jsonWebToken}}

### 通过订单id获取订单
GET {{url}}/api/order/get/{{order_id}}
{{jsonWebToken}}

### 根据订单id修改订单内容
PATCH {{url}}/api/order/{{order_id}}/update
{{jsonWebToken}}
{{json}}

{
    "num": 5
}

### 根据订单id取消订单
DELETE {{url}}/api/order/{{order_id}}/remove
{{jsonWebToken}}

### 管理员注册
# @name admin_token
POST  {{url}}/api/admin/user/signup
{{json}}

{
    "username": "123",
    "password": "87654321"
}

### 管理员登录
# @name admin_token
POST  {{url}}/api/admin/user/login
{{json}}

{
    "username": "123",
    "password": "87654321"
}

### 管理员新建产品
POST {{url}}/api/admin/product/add
{{adminJsonWebToken}}
{{json}}

{
    "product_id": "hjgfhsjfhgjdfhjd",
    "type_name": "网帘，一幅",
    "price": "¥ 39.90"
}

### 管理员根据产品id修改产品信息
PATCH {{url}}/api/admin/product/hjgfhsjfhgjdfhjd/update
{{adminJsonWebToken}}
{{json}}

{
    "type_name": "网帘，两幅",
    "price": "¥ 29.90"
}

### 管理员根据产品id删除产品
DELETE {{url}}/api/admin/product/hjgfhsjfhgjdfhjd/delete
{{adminJsonWebToken}}

### 管理员查看所有订单
GET {{url}}/api/admin/order/all/1/{all}
{{adminJsonWebToken}}

### 管理员根据订单id确认/取消确认订单
PATCH {{url}}/api/admin/order/{{order_id}}/true
{{adminJsonWebToken}}

### 管理员查看所有用户
Get {{url}}/api/admin/user_control/all/1
{{adminJsonWebToken}}

### 管理员封禁/解封用户
PATCH {{url}}/api/admin/user_control/ljd9726@163.com/true
{{adminJsonWebToken}}
